CarWeb/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CarWeb.Models;

namespace CarWeb.Controllers
{
    public class AboutController : Controller
    {
        private readonly ILogger<AboutController> _logger;
        private readonly IMapper _mapper;

        public AboutController(ILogger<AboutController> logger,
            IMapper mapper)
        {
            _logger = logger;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

CarWeb/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CarWeb.Models;

namespace CarWeb.Controllers
{
    public class BlogController : Controller
    {
        private readonly ILogger<BlogController> _logger;
        private readonly IMapper _mapper;

        public BlogController(ILogger<BlogController> logger,
            IMapper mapper)
        {
            _logger = logger;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

CarWeb/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CarWeb.Models;
using CarWeb.Models.Car;
using CarWeb.Services.Interfaces;

namespace CarWeb.Controllers
{
    public class CarController : Controller
    {
        private readonly ILogger<CarController> _logger;
        private readonly IMapper _mapper;
        private readonly ICarService _carService;

        public CarController(ILogger<CarController> logger, ICarService carService, IMapper mapper)
        {
            _carService = carService;
            _logger = logger;
            _mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var carList = await _carService.GetAll(new ContractRequest<BaseRequest>());
            return View(carList.Data.Cars);
        }
    }
}

CarWeb/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using CarWeb.Mapping;
using CarWeb.Models;
using CarWeb.Models.ViewModels.Contact;
using CarWeb.Services.Interfaces.Contact;

namespace CarWeb.Controllers
{
    public class ContactController : Controller
    {
        private readonly ILogger<ContactController> _logger;
        private readonly IMapper _mapper;
        private readonly IContactService _contactService;

        public ContactController(ILogger<ContactController> logger, IContactService contactService,
            IMapper mapper)
        {
            _logger = logger;
            _mapper = mapper;
            _contactService = contactService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        //[Authorize]
        public async Task<IActionResult> AddContact([FromBody] ContactViewModel request)
        {
            try
            {
                var requestContact = request.ToContractRequest(_mapper);
                var contactAdd = await _contactService.Add(requestContact);
                return Json(contactAdd.Data.Contact);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Getting Contact");
                return Json(null);
            }
        }
    }
}

CarWeb/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">

<head>
    <title>Car Rent &mdash; Free Website Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=DM+Sans:300,400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/fonts/icomoon/style.css">

    @*<link rel="stylesheet" href="~/css/bootstrap.min.css">*@
    @*<link rel="stylesheet" href="~/lib/dist/css/bootstrap.min.css">*@
    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    @*<link rel="stylesheet" href="~/css/bootstrap-datepicker.css">*@
    <link rel="stylesheet" href="~/css/jquery.fancybox.min.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">
    <link rel="stylesheet" href="~/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="~/css/aos.css">

    <!-- MAIN CSS -->
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/limousine.css">

    <link rel="stylesheet" href="~/css/stepper.min.css">

    @*<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />*@
    <link rel="stylesheet" type="text/css" href="~/css/template/main.css">
    <link rel="stylesheet" type="text/css" href="~/css/select2.css">
    <link rel="stylesheet" type="text/css" href="~/css/select2-bootstrap.css">
    <link href="~/lib/bootstrap-fileinput/css/fileinput.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/jquery-autocomplete/jquery-ui.css">


    <link href="~/css/template/main.css" rel="stylesheet" />
    <link href="~/css/template/util.css" rel="stylesheet" />

    <link href="~/lib/fontawesome/css/font-awesome.css" rel="stylesheet" />
    @if (IsSectionDefined("Styles"))
    {@RenderSection("Styles", required: false)}
</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

    <div class="site-wrap" id="home-section" style="background: #f6f5f5;">

        <div class="site-mobile-menu site-navbar-target">
            <div class="site-mobile-menu-header">
                <div class="site-mobile-menu-close mt-3">
                    <span class="icon-close2 js-menu-toggle"></span>
                </div>
            </div>
            <div class="site-mobile-menu-body"></div>
        </div>



        <header class="site-navbar site-navbar-target" role="banner">

            <div class="container">
                <div class="row align-items-center position-relative">

                    <div class="col-3">
                        <div class="site-logo">
                            <a asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" style="width:140px;" alt="App Logo" class="img-responsive" /></a>
                        </div>
                    </div>

                    <div class="col-9  text-right">
                        <span class="d-inline-block d-lg-none"><a href="#" class="text-white site-menu-toggle js-menu-toggle py-5 text-white"><span class="icon-menu h3 text-white"></span></a></span>
                        <nav class="site-navigation text-right ml-auto d-none d-lg-block" role="navigation">
                            <ul class="site-menu main-menu js-clone-nav ml-auto ">
                                <li><a asp-controller="Home" asp-action="Index" id="home" class="nav-link">Inicio</a></li>
                                <li><a asp-controller="Service" asp-action="Index" id="services" class="nav-link">Services</a></li>
                                <li><a asp-controller="Car" asp-action="Index" id="cars" class="nav-link">Cars</a></li>
                                <li><a asp-controller="About" asp-action="Index" id="about" class="nav-link">About</a></li>
                                <li><a asp-controller="Blog" asp-action="Index" id="blog" class="nav-link">Blog</a></li>
                                <li><a asp-controller="Contact" asp-action="Index" id="contact" class="nav-link">Contacto</a></li>
                                <li><a asp-controller="Security" asp-action="Login" id="Login" class="nav-link">Iniciar Sesión</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>

        </header>
        @RenderBody()

        <!--

         <footer class="site-footer">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3">
                        <h2 class="footer-heading mb-4">About Us</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
                    </div>
                    <div class="col-lg-8 ml-auto">
                        <div class="row">
                            <div class="col-lg-3">
                                <h2 class="footer-heading mb-4">Quick Links</h2>
                                <ul class="list-unstyled">
                                    <li><a href="#">About Us</a></li>
                                    <li><a href="#">Testimonials</a></li>
                                    <li><a href="#">Terms of Service</a></li>
                                    <li><a href="#">Privacy</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-3">
                                <h2 class="footer-heading mb-4">Quick Links</h2>
                                <ul class="list-unstyled">
                                    <li><a href="#">About Us</a></li>
                                    <li><a href="#">Testimonials</a></li>
                                    <li><a href="#">Terms of Service</a></li>
                                    <li><a href="#">Privacy</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-3">
                                <h2 class="footer-heading mb-4">Quick Links</h2>
                                <ul class="list-unstyled">
                                    <li><a href="#">About Us</a></li>
                                    <li><a href="#">Testimonials</a></li>
                                    <li><a href="#">Terms of Service</a></li>
                                    <li><a href="#">Privacy</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                </ul>
                            </div>
                            <div class="col-lg-3">
                                <h2 class="footer-heading mb-4">Quick Links</h2>
                                <ul class="list-unstyled">
                                    <li><a href="#">About Us</a></li>
                                    <li><a href="#">Testimonials</a></li>
                                    <li><a href="#">Terms of Service</a></li>
                                    <li><a href="#">Privacy</a></li>
                                    <li><a href="#">Contact Us</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row pt-5 mt-5 text-center">
                    <div class="col-md-12">
                        <div class="border-top pt-5">
                            <p>

                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart text-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>

                            </p>
                        </div>
                    </div>

                </div>
            </div>
        </footer>-->


    </div>

    <script type="text/javascript">
        var baseUrl = "@Url.Content("~/")";
    </script>
    @*<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>*@

    @*<script src="~/js/jquery-3.3.1.min.js"></script>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/js/jquery-ui.js"></script>
    <script src="~/js/popper.min.js"></script>
    @*<script type="text/javascript" src="~/js/bootstrap.min.js"></script>*@
    <script type="text/javascript" src="~/lib/dist/js/bootstrap.min.js"></script>

    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.sticky.js"></script>
    <script src="~/js/jquery.waypoints.min.js"></script>
    <script src="~/js/jquery.animateNumber.min.js"></script>
    <script src="~/js/jquery.fancybox.min.js"></script>
    <script src="~/js/jquery.easing.1.3.js"></script>
    <script src="~/js/aos.js"></script>
    <script src="~/js/stepper.min.js"></script>
    <script src="~/lib/bootstrap-fileinput/js/fileinput.min.js"></script>
    <script src="~/lib/bootstrap-fileinput/themes/fa/theme.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    <script src="~/js/main.js"></script>
    <script src="~/js/Util/serviceTypeEnum.js"></script>
    <script src="~/js/Util/helper.js"></script>
    <script src="~/js/About/_about.js"></script>
    <script src="~/js/Blog/_blog.js"></script>
    <script src="~/js/Car/_car.js"></script>
    @RenderSection("scripts", required: false)


    @*<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>*@
    @*<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
        <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>*@

    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&libraries=places&key=AIzaSyDPXB9KbhsRHFjP-snur0HjO-x-EJSxFKM"></script>
</body>

</html>